version: '3.8'
services:
  inventory_management_fe:
    build: .
    container_name: inventory-management-fe
    ports:
      - '3003:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: npm run build && npm start
    restart: unless-stopped
    networks:
      - logistics_network

networks:
  logistics_network:
    external: true
